apiVersion: v1
name: redis-operator
version: 4.0.0
# appVersion is the Docker image tag. Must include leading "v".
# Chart version 4.0.0 -> image tag v4.0.0
appVersion: v4.0.0
description: A Helm chart for the Redis Operator
home: https://github.com/saremox/redis-operator
keywords:
  - "golang"
  - "operator"
  - "cluster"
sources:
  - https://github.com/saremox/redis-operator
kubeVersion: ">=1.21.0-0"
