appVersion: 4.0.0
apiVersion: v1
description: A Helm chart for the Saremox Redis Operator
name: redis-operator
version: 4.0.0
home: https://github.com/saremox/redis-operator
keywords:
  - "golang"
  - "operator"
  - "cluster"
sources:
  - https://github.com/saremox/redis-operator
kubeVersion: ">=1.21.0-0"
